In [21]:
import pandas as pd
import numpy as np
customers = pd.read_csv(r"C:\Users\RohanS\Documents\data retail\olist_customers_dataset.csv")

orders = pd.read_csv(r"C:\Users\RohanS\Documents\data retail\olist_orders_dataset.csv")

order_items = pd.read_csv(r"C:\Users\RohanS\Documents\data retail\olist_order_items_dataset.csv")

payments = pd.read_csv(r"C:\Users\RohanS\Documents\data retail\olist_order_payments_dataset.csv")

products = pd.read_csv(r"C:\Users\RohanS\Documents\data retail\olist_products_dataset.csv")

reviews = pd.read_csv(r"C:\Users\RohanS\Documents\data retail\olist_order_reviews_dataset.csv")

sellers = pd.read_csv(r"C:\Users\RohanS\Documents\data retail\olist_sellers_dataset.csv")

translation = pd.read_csv(r"C:\Users\RohanS\Documents\data retail\product_category_name_translation.csv")

geolocation = pd.read_csv(r"C:\Users\RohanS\Documents\data retail\olist_geolocation_dataset.csv")

In [22]:
datasets = {
    "customers": customers,
    "orders": orders,
    "order_items": order_items,
    "payments": payments,
    "products": products,
    "reviews": reviews,
    "sellers": sellers,
    "translation": translation,
    "geolocation": geolocation
}

for name, df in datasets.items():
    print("="*50)
    print(name.upper())
    print(df.shape)
    print(df.columns.tolist())

==================================================
CUSTOMERS
(99441, 5)
['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']
==================================================
ORDERS
(99441, 8)
['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']
==================================================
ORDER_ITEMS
(112650, 7)
['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']
==================================================
PAYMENTS
(103886, 5)
['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']
==================================================
PRODUCTS
(32951, 9)
['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']
==================================================
REVIEWS
(99224, 7)
['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']
==================================================
SELLERS
(3095, 4)
['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']
==================================================
TRANSLATION
(71, 2)
['product_category_name', 'product_category_name_english']
==================================================
GEOLOCATION
(1000163, 5)
['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng', 'geolocation_city', 'geolocation_state']

In [23]:
fact_sales = orders.merge(
    customers,
    on="customer_id",
    how="left"
)

fact_sales = fact_sales.merge(
    order_items,
    on="order_id",
    how="left"
)

fact_sales = fact_sales.merge(
    products,
    on="product_id",
    how="left"
)

fact_sales = fact_sales.merge(
    translation,
    on="product_category_name",
    how="left"
)

fact_sales = fact_sales.merge(
    payments,
    on="order_id",
    how="left"
)

fact_sales = fact_sales.merge(
    reviews,
    on="order_id",
    how="left"
)

fact_sales = fact_sales.merge(
    sellers,
    on="seller_id",
    how="left"
)

print(fact_sales.shape)
fact_sales.to_csv(
    r"C:\Users\RohanS\Documents\data retail\fact_sales.csv",
    index=False
)

(119143, 40)

In [24]:

fact_sales['order_purchase_timestamp'] = pd.to_datetime(fact_sales['order_purchase_timestamp'])

fact_sales['order_delivered_customer_date'] = pd.to_datetime(fact_sales['order_delivered_customer_date'])

fact_sales['order_estimated_delivery_date'] = pd.to_datetime(fact_sales['order_estimated_delivery_date'])

fact_sales['order_approved_at'] = pd.to_datetime(fact_sales['order_approved_at'])

In [25]:

fact_sales_fe=fact_sales.copy()

In [26]:
fact_sales_fe["approval_time"]=fact_sales_fe['order_approved_at']-fact_sales_fe['order_purchase_timestamp']

In [27]:
fact_sales_fe["delivery_days"]=fact_sales_fe['order_delivered_customer_date']-fact_sales_fe['order_purchase_timestamp']

In [28]:
fact_sales_fe["delivery_delay"]=fact_sales_fe['order_estimated_delivery_date']-fact_sales_fe['order_delivered_customer_date']

In [29]:
fact_sales_fe['product_volume_cm3']=fact_sales_fe['product_length_cm']*fact_sales_fe["product_height_cm"]*fact_sales_fe["product_width_cm"]

In [30]:
fact_sales_fe['freight_%']=fact_sales_fe["freight_value"]*100/fact_sales_fe['price']

In [31]:




fact_sales_fe['order_month']=fact_sales_fe['order_purchase_timestamp'].dt.strftime("%B")
fact_sales_fe['order_yaer']=fact_sales_fe['order_purchase_timestamp'].dt.year
fact_sales_fe['order_day']=fact_sales_fe['order_purchase_timestamp'].dt.day_name()
fact_sales_fe['order_hour']=fact_sales_fe['order_purchase_timestamp'].dt.hour
print(fact_sales.shape)
fact_sales_fe.to_csv(
    r"C:\Users\RohanS\Documents\data retail processed\fact_sales_fe.csv",
    index=False)
fact_sales_fe

(119143, 40)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,seller_state,approval_time,delivery_days,delivery_delay,product_volume_cm3,freight_%,order_month,order_yaer,order_day,order_hour
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,SP,0 days 00:10:42,8 days 10:28:40,7 days 02:34:47,1976.0,29.076359,October,2017,Monday,10
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,SP,0 days 00:10:42,8 days 10:28:40,7 days 02:34:47,1976.0,29.076359,October,2017,Monday,10
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,SP,0 days 00:10:42,8 days 10:28:40,7 days 02:34:47,1976.0,29.076359,October,2017,Monday,10
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,...,SP,1 days 06:42:50,13 days 18:46:08,5 days 08:32:15,4693.0,19.174389,July,2018,Tuesday,20
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,SP,0 days 00:16:34,9 days 09:27:40,17 days 05:53:31,9576.0,12.020013,August,2018,Wednesday,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119138,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,da62f9e57a76d978d02ab5362c509660,11722,...,SP,0 days 00:11:39,22 days 04:38:58,1 days 06:22:04,16000.0,11.492281,February,2018,Tuesday,12
119139,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,737520a9aad80b3fbbdad19b66b37b30,45920,...,SP,0 days 00:17:33,24 days 20:37:34,5 days 12:35:43,63360.0,31.564639,August,2017,Sunday,14
119140,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,5097a5312c8b157bb7be58ae360ef43c,28685,...,MG,0 days 00:07:54,17 days 02:04:27,20 days 00:27:06,8000.0,22.551253,January,2018,Monday,21
119141,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,5097a5312c8b157bb7be58ae360ef43c,28685,...,MG,0 days 00:07:54,17 days 02:04:27,20 days 00:27:06,8000.0,22.551253,January,2018,Monday,21
119142,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,60350aa974b26ff12caad89e55993bd6,83750,...,SP,0 days 14:22:58,7 days 16:11:00,17 days 10:51:30,1680.0,26.802920,March,2018,Thursday,20

In [32]:
product_mart = (
    fact_sales_fe
    .groupby("product_id")
    .agg(
        category=("product_category_name_english","first"),
        total_revenue=("price","sum"),
        units_sold=("order_item_id","count"),
        avg_price=("price","mean"),
        avg_review=("review_score","mean"),
        avg_freight=("freight_value","mean"),
        total_orders=("order_id","nunique")
    )
    .reset_index()
)
print(fact_sales.shape)
product_mart.to_csv(
    r"C:\Users\RohanS\Documents\data retail processed\product_mart.csv",
    index=False)

(119143, 40)

In [33]:
customer_mart = (
    fact_sales_fe
    .groupby("customer_unique_id")
    .agg(
        total_orders=("order_id","nunique"),
        total_spent=("payment_value","sum"),
        avg_review=("review_score","mean"),
        last_purchase=("order_purchase_timestamp","max")
    )
    .reset_index()
)
print(fact_sales.shape)
customer_mart.to_csv(
    r"C:\Users\RohanS\Documents\data retail processed\customer_mart.csv",
    index=False)

(119143, 40)

In [34]:
seller_mart = (
    fact_sales_fe
    .groupby("seller_id")
    .agg(
        total_orders=("order_id","nunique"),
        total_revenue=("price","sum"),
        avg_delivery=("delivery_days","mean"),
        avg_review=("review_score","mean")
    )
    .reset_index()
)
print(fact_sales.shape)
seller_mart.to_csv(
    r"C:\Users\RohanS\Documents\data retail processed\seller_mart.csv",
    index=False)

(119143, 40)

In [35]:
geo_mart = (
    fact_sales_fe
    .groupby("customer_state")
    .agg(
        revenue=("price","sum"),
        orders=("order_id","nunique"),
        customers=("customer_unique_id","nunique")
    )
    .reset_index()
)
print(fact_sales.shape)
geo_mart.to_csv(
    r"C:\Users\RohanS\Documents\data retail processed\geo_mart.csv",
    index=False)

(119143, 40)

In [37]:
products

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0
...,...,...,...,...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,45.0,67.0,2.0,12300.0,40.0,40.0,40.0
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,41.0,971.0,1.0,1700.0,16.0,19.0,16.0
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,50.0,799.0,1.0,1400.0,27.0,7.0,27.0
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,156.0,2.0,700.0,31.0,13.0,20.0
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,58.0,309.0,1.0,2083.0,12.0,2.0,7.0